services:
  web:
    image: node:20-bullseye-slim
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=0
      - WATCHPACK_POLLING=false
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - ./:/app
      - /app/node_modules
    command: sh -lc "npm install && npm run dev -- -p 3000"

